version: '2'

volumes:
    mysql_data:
        driver: local

services:
  php:
    build: ./docker/php/
    container_name: php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
      - apache
    env_file: ./.env
  apache:
    build: ./docker/apache/
    container_name: apache
    networks:
        default:
          aliases:
              - ${DOMAIN_LOCAL}
    ports:
        - 80:80
    volumes:
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./public:${DIR_WEB_ROOT}:z
      - .:${DIR_PROJECT_ROOT}:z
    env_file: ./.env
  mysql:
    build: ./docker/mysql/
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mvc
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyamdin
      environment:
          - PMA_ARBITRARY=1
      ports:
          - "8001:80"
      volumes:
          - /sessions

networks:
  default:
